Repository holoviz/datashader, pull requests merged in 2019-02, with the labels that each got.

#709 Expanded 8_Geography.ipynb to include other geo-related functions
  examples/user_guide/8_Geography.ipynb
Labels: in progress

#711 Fixing up website formatting
  README.md
  doc/_static/site.css
  doc/_templates/layout.html
  doc/about.rst
  doc/conf.py
  doc/getting_started/index.rst
  doc/index.rst
  doc/latest_news.html
  examples/getting_started/index.ipynb
  examples/index.ipynb
Labels: ready

#708 Updated docs and examples for SpatialPointsFrame
  datashader/core.py
  datashader/geo.py
  datashader/spatial/__init__.py
  datashader/spatial/points.py
  datashader/tests/test_spatial.py
  examples/dashboard.yml
  examples/datasets.yml
  examples/topics/census.ipynb
  examples/topics/osm-1billion.ipynb
  examples/topics/osm.ipynb
  examples/user_guide/2_Points.ipynb
Labels: in progress, wip

#714 Website Tweak
  doc/latest_news.html
Labels: in progress

#707 Removed precedence from parameter definitions in dashboard
  examples/dashboard.ipynb
Labels: in progress

#717 Fix memory explosion when auto-calculating canvas range extents with dask
  datashader/dask.py
  datashader/glyphs.py
  datashader/tests/test_dask.py
Labels: in progress
